<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Licenses</name>
   <tag></tag>
   <elementGuidId>a638a957-1b61-4805-b1bc-a403a3e31c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.horizontalMenuItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[span[text()='Licenses']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Licenses&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5ee0521-f32b-4e17-a249-60d82ff8afce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>horizontalMenuItem</value>
      <webElementGuid>0df7391a-3e22-4285-b338-363e2ebf0e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00ab9d7c-eccb-4430-90da-f429bc34ef63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f67b6389-49b2-4eca-9529-693525089daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>navigation-list</value>
      <webElementGuid>a6517099-7bb1-4b14-a23e-7e05060453df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Licenses</value>
      <webElementGuid>2a61d97e-845d-4f6e-817c-adc4c1404bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commThemeNav&quot;)/div[1]/div[@class=&quot;ui-widget&quot;]/div[@class=&quot;comm-navigation forceCommunityMultiLevelNavigation&quot;]/community_navigation-multi-level-navigation-container[1]/community_navigation-multi-level-navigation[@class=&quot;multi-level-navigation&quot;]/nav[1]/ul[@class=&quot;slds-list_horizontal&quot;]/li[@class=&quot;textMenuItem slds-p-vertical_x-small slds-p-horizontal_small horizontalMenuItemContainer&quot;]/button[@class=&quot;horizontalMenuItem&quot;]</value>
      <webElementGuid>e719ef4f-85ca-4c14-b25a-9be5a615a8aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/div/community_navigation-multi-level-navigation-container/community_navigation-multi-level-navigation/nav/ul/li[2]/button</value>
      <webElementGuid>c3cea9b0-7542-4b0a-a3c5-1f52fe070b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::button[1]</value>
      <webElementGuid>9f3cd840-102e-4cce-b8b9-cacfa7dc5c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ColumbiaPortal'])[1]/following::button[1]</value>
      <webElementGuid>f5db6bd7-7b23-46b2-a325-28280edbd916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Applications'])[1]/preceding::button[1]</value>
      <webElementGuid>ac794625-2871-4846-9546-2be19438639a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>095cfe13-3fd6-4f45-961e-06d887f49d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Licenses' or . = 'Licenses')]</value>
      <webElementGuid>c6b160e8-b243-42a9-8461-985ffc9998d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
