<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Applications</name>
   <tag></tag>
   <elementGuidId>410a0a92-a675-4a77-89f9-9246b23962e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[a[@data-label=&quot;Applications&quot;]]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slds-size_small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Applications&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a58c3f98-746e-4ae5-9871-761cc281b651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-size_small</value>
      <webElementGuid>63b04841-b196-4712-8e27-6f16298dee50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Applications</value>
      <webElementGuid>fe1523a3-dd5a-4ba7-95cd-8a30e1557661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Application__c&quot;)/div[@class=&quot;slds-size_small&quot;]</value>
      <webElementGuid>aa90637b-c6e6-4329-9f13-022afc8af4e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Application__c']/div</value>
      <webElementGuid>70f9fe72-ca22-4bc4-bc25-b2165b87669f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items'])[1]/following::div[2]</value>
      <webElementGuid>3f620742-92ba-44bc-86a0-0a66ad0a4fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/following::div[3]</value>
      <webElementGuid>df4b0488-a1a6-49f3-aeb8-80266647c5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::div[1]</value>
      <webElementGuid>a3106490-1f6a-4040-9d85-b28c2b07efe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-menu-item/a/div</value>
      <webElementGuid>715a55c4-2b64-49d1-ba97-38aa54462aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Applications' or . = 'Applications')]</value>
      <webElementGuid>5e7109f0-8d40-4140-be87-d194d788933a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
