<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slot_APP-24-00094</name>
   <tag></tag>
   <elementGuidId>47bde528-91c2-45c3-ad78-a4a05dbd666e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>slot[name=&quot;primaryField&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//slot[@name='primaryField']/*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>records-highlights2 slot >> internal:has-text=&quot;APP-24-00094&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>slot</value>
      <webElementGuid>65f1ad99-c6e0-459e-b3dd-fc51ccc156da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-page-header__title slds-m-right--small slds-align-middle slds-line-clamp clip-text</value>
      <webElementGuid>7ffa1821-ad19-44b6-b0fc-a1355fe73368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primaryField</value>
      <webElementGuid>1c134bcc-120e-431f-b629-cf670c1142d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APP-24-00094</value>
      <webElementGuid>c2b5d89b-62c0-4fd9-b28d-b47bc6ecdff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;oneRecordHomeFlexipage2Wrapper&quot;]/div[@class=&quot;recordHomeFlexipage2&quot;]/one-record-home-flexipage2[1]/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-application_-record_-page1___-application__c___-v-i-e-w___-l-m-t___1720624677000[@class=&quot;adg-rollup-wrapped&quot;]/forcegenerated-flexipage_application_record_page1_application__c__view_js___lmt___1720624677000[@class=&quot;forcegenerated-flexipage-module&quot;]/record_flexipage-desktop-record-page-decorator[1]/div[@class=&quot;record-page-decorator&quot;]/records-record-layout-event-broker[1]/slot[1]/slot[1]/flexipage-record-home-template-desktop2[@class=&quot;forcegenerated-flexipage-template&quot;]/div[@class=&quot;slds-grid slds-wrap&quot;]/div[@class=&quot;slds-col slds-size_1-of-1 row region-header&quot;]/slot[1]/flexipage-component2[1]/slot[1]/records-lwc-highlights-panel[1]/records-lwc-record-layout[1]/forcegenerated-highlightspanel_application__c___012d10000003kuliaa___compact___view___recordlayout2[@class=&quot;forcegenerated-record-layout2&quot;]/records-highlights2[1]/div[@class=&quot;highlights slds-clearfix slds-page-header slds-page-header_record-home fixed-position&quot;]/div[@class=&quot;slds-grid primaryFieldRow&quot;]/div[@class=&quot;slds-grid slds-col slds-has-flexi-truncate&quot;]/div[@class=&quot;slds-media__body&quot;]/h1[1]/slot[@class=&quot;slds-page-header__title slds-m-right--small slds-align-middle slds-line-clamp clip-text&quot;]</value>
      <webElementGuid>845d4209-7161-403a-995a-a88153c508a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//slot[@name='primaryField']</value>
      <webElementGuid>4de82631-1766-4404-9b85-198c67843deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-application_-record_-page1___-application__c___-v-i-e-w___-l-m-t___1720624677000/forcegenerated-flexipage_application_record_page1_application__c__view_js___lmt___1720624677000/record_flexipage-desktop-record-page-decorator/div/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div/slot/flexipage-component2/slot/records-lwc-highlights-panel/records-lwc-record-layout/forcegenerated-highlightspanel_application__c___012d10000003kuliaa___compact___view___recordlayout2/records-highlights2/div/div/div/div[2]/h1/slot</value>
      <webElementGuid>d1b1920a-9dc3-4900-a5a2-253cabf12672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[2]/following::slot[1]</value>
      <webElementGuid>8636a21b-4942-41a0-b012-e17cbf187417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::slot[7]</value>
      <webElementGuid>b1a6c4e8-2577-4d67-8ac3-2cceba0e1881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Outstanding Items'])[1]/preceding::slot[3]</value>
      <webElementGuid>cb0ac970-b0e5-473a-a8af-bb1ed60ab0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/slot</value>
      <webElementGuid>b19985be-69a5-4598-8569-da096fb07f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//slot[@name = 'primaryField' and (text() = 'APP-24-00094' or . = 'APP-24-00094')]</value>
      <webElementGuid>90e4027d-099c-4cad-9812-eed48d45dc66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
