<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MassageTherapy_slds-radio_faux</name>
   <tag></tag>
   <elementGuidId>d176e1c1-a5ac-41df-bcf5-6dee57f8db07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio-button-label-3-212 > span.slds-radio_faux</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr/td[following-sibling::th[@data-cell-value=&quot;Therapist&quot;]]/*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;Select Item 3 Choose a Row to Select&quot;i] >> span >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bff812ca-8934-420f-903f-daa561046f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-radio_faux</value>
      <webElementGuid>10ca6f4f-d52f-40d8-9100-58cf79ebacfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-label-3-212&quot;)/span[@class=&quot;slds-radio_faux&quot;]</value>
      <webElementGuid>3b5bfadf-1548-43d9-8940-cf830f4d935b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='radio-button-label-3-212']/span</value>
      <webElementGuid>17fc534a-ce1b-4919-ae93-6b60f3b5f5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/lightning-primitive-cell-checkbox/span/label/span</value>
      <webElementGuid>380cd50b-fb60-4da0-ab8c-a28766a421e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
