<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_6 of 6 items</name>
   <tag></tag>
   <elementGuidId>3c437e4e-6055-48b5-8890-e509fcab2762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.table-rows-count</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[span[@class=&quot;table-rows-count&quot;]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;6 of 6 items&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>541803ef-9278-43d8-81d8-271d906fe43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-rows-count</value>
      <webElementGuid>cf7745b9-1cfe-4f52-a518-44fc79f36d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6 of 6 items</value>
      <webElementGuid>2281de9c-d49b-4753-b3d0-759b6a1752c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flowruntime_datatable_info_message_display-108&quot;)/span[@class=&quot;table-rows-count&quot;]</value>
      <webElementGuid>13f3c88b-7aa1-4333-95f2-4ff7402a99a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='flowruntime_datatable_info_message_display-108']/span</value>
      <webElementGuid>70808e13-2b9f-4c72-9e58-1fac9a9e4929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Before you continue'])[1]/following::span[2]</value>
      <webElementGuid>89886e59-c7a9-468d-844e-4b00e929d210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/following::span[3]</value>
      <webElementGuid>c7faf804-dae5-474f-a6d4-c77dd68628d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigation Mode'])[1]/preceding::span[2]</value>
      <webElementGuid>2b8df01f-cb0e-45fa-8fcf-aa9ae53d482e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Mode'])[1]/preceding::span[3]</value>
      <webElementGuid>83fe1460-3672-4bfd-a02a-a8c1eba8aa51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6 of 6 items']/parent::*</value>
      <webElementGuid>2be0d785-352d-42a7-a299-8549efa2c665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p/span</value>
      <webElementGuid>0018a91b-9dfc-4c32-a26d-2f96427a015c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '6 of 6 items' or . = '6 of 6 items')]</value>
      <webElementGuid>563325dd-3868-4ad1-b22b-af822351279b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
