<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finish</name>
   <tag></tag>
   <elementGuidId>9b2bed92-dffa-4d1b-bac4-3214071bb150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='Finish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Finish&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28542642-5b4a-43ee-8240-b205bc1d5877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand</value>
      <webElementGuid>7117eaf3-8a79-4d9f-991b-202783cf167a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee61a492-b5a3-4ca1-856d-9fdb06728094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7ab08d0-ae67-4d1a-b8d9-c7a6014abcc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Finish</value>
      <webElementGuid>96e6523c-5d3a-4361-bb47-ef5a69373a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77974d82-fef8-4f26-b406-1e7742c8047f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kx-scope</name>
      <type>Main</type>
      <value>button-brand</value>
      <webElementGuid>5c56a3f4-38fa-41d8-8045-ab3da33070fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kx-type</name>
      <type>Main</type>
      <value>ripple</value>
      <webElementGuid>263e8dc5-4e26-4d20-b0cc-5eb23e7a5392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finish</value>
      <webElementGuid>eaea1ee6-c3f5-43ac-8448-918fda24ff82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;slds-no-wcag&quot;]/body[@class=&quot;null Applications comm-page-custom-License Applications&quot;]/div[@class=&quot;themeLayoutStarterWrapper isHeroUnderHeader-false isHeaderPinned-true siteforceThemeLayoutStarter&quot;]/div[@class=&quot;body isPageWidthFixed-true&quot;]/div[@class=&quot;siteforceDynamicLayout siteforceContentArea&quot;]/div[1]/div[@class=&quot;ui-widget&quot;]/div[@class=&quot;cb-section forceCommunitySection&quot;]/div[@class=&quot;cb-section_row slds-grid slds-wrap slds-large-nowrap&quot;]/div[@class=&quot;cb-section_column slds-size_12-of-12 slds-max-medium-size_12-of-12&quot;]/div[1]/div[@class=&quot;ui-widget&quot;]/article[@class=&quot;slds-card flowRuntimeForFlexipage forceCommunityFlowCommunity&quot;]/div[1]/flowruntime-flow[1]/flowruntime-lwc-body[1]/div[@class=&quot;flowruntimeBody flowruntimeBody__lwc slds-card__body slds-p-horizontal_small&quot;]/flowruntime-list-container[1]/div[1]/flowruntime-base-section[1]/div[1]/flowruntime-screen-field[9]/flowruntime-lwc-field[@class=&quot;field-element&quot;]/div[@class=&quot;container&quot;]/clariti-flow-button-bar[1]/div[@class=&quot;slds-clearfix&quot;]/div[@class=&quot;slds-float_right notToggle&quot;]/lightning-button[2]/button[@class=&quot;slds-button slds-button_brand&quot;]</value>
      <webElementGuid>65df2762-96ac-4504-99cb-0b8ed29b27d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='Finish']</value>
      <webElementGuid>107c64bc-3402-4fd5-86d1-cb35ed236d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Documents'])[2]/following::button[1]</value>
      <webElementGuid>084199b1-6be8-4da1-96d1-3e16d7d44358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='False'])[3]/following::button[2]</value>
      <webElementGuid>f39a0ea0-65d5-46cc-b3ae-f0a969b2242b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[2]/preceding::button[1]</value>
      <webElementGuid>bada99f1-83a3-4640-8c1d-772c2c6886e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finish']/parent::*</value>
      <webElementGuid>215930e1-129c-4e75-9c8a-a352cea048b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-button[2]/button</value>
      <webElementGuid>5848bbf9-d547-454f-bf26-ab0b476c5405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Finish' or . = 'Finish')]</value>
      <webElementGuid>4121dbfe-5d53-47ef-b834-f97e938512c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
